INSERT INTO IBRAIN_GROUP(GROUP_NAME) VALUES ('STUDENT');
INSERT INTO IBRAIN_GROUP(GROUP_NAME) VALUES ('ADMIN');
INSERT INTO IBRAIN_GROUP(GROUP_NAME) VALUES ('TUTOR');
INSERT INTO IBRAIN_GROUP(GROUP_NAME) VALUES ('MODERATOR');
